#!/usr/bin/env python3

import sys
import serial
import struct

if len(sys.argv) != 2:
    print("Expecting a file name")
    sys.exit(1)

filename = sys.argv[1]

s = serial.Serial("/dev/ttyUSB0",
    baudrate = 9600,
    bytesize = serial.EIGHTBITS,
    parity = serial.PARITY_NONE,
    stopbits = serial.STOPBITS_ONE,
    timeout = None,
    xonxoff = False,
    rtscts = False,
    dsrdtr = False)

s.flushInput()
s.flushOutput()

f = open(filename, "rb")
d = f.read()
f.close()

length = len(d) >> 1
s.write(bytes([(length>>8) & 0xff, length & 0xff]))

csum_calc = 0
for b in range(0, length):
    csum_calc += d[b*2]*256 + d[b*2+1]
    csum_calc &= 0xffff

s.write(bytes([(csum_calc>>8) & 0xff, csum_calc & 0xff]))

s.write(d)

s.close()
