#!/usr/bin/env python3

import sys
import serial
import struct

if len(sys.argv) != 2:
    print("Expecting a file name")
    sys.exit(1)

filename = sys.argv[1]

s = serial.Serial("/dev/ttyUSB1",
    baudrate = 9600,
    bytesize = serial.EIGHTBITS,
    parity = serial.PARITY_NONE,
    stopbits = serial.STOPBITS_ONE,
    timeout = None,
    xonxoff = False,
    rtscts = False,
    dsrdtr = False)

s.flushInput()
s.flushOutput()

f = open(filename, "rb")
d = f.read()
s.write(d)

f.close()

s.close()
