#!/usr/bin/env python3

import sys
import serial
import struct

if len(sys.argv) != 2:
    print("Expecting a file name")
    sys.exit(1)

filename = sys.argv[1]

s = serial.Serial("/dev/ttyUSB0",
    baudrate = 9600,
    bytesize = serial.EIGHTBITS,
    parity = serial.PARITY_NONE,
    stopbits = serial.STOPBITS_ONE,
    timeout = 2,
    xonxoff = False,
    rtscts = False,
    dsrdtr = False)

s.flushInput()
s.flushOutput()

f = open(filename, "wb")
while True:
    d = s.read(1)
    if not d:
        break
    f.write(d)

f.close()

s.close()
